export const tableData = [
    { name: "Akshay Kumar", age: 27, gender: "MALE" },
    { name: "Pankaj Sharma", age: 28, gender: "MALE" },
    { name: "Shubham Soni", age: 28, gender: "MALE" },
    { name: "Nitish Jha", age: 21, gender: "MALE" },
    { name: "Akshaya Sivshankar ", age: 21, gender: "FEMALE" },
    { name: "Parbhas", age: 35, gender: "MALE" },
    { name: "Supriya", age: 25, gender: "FEMALE" },
    { name: "Nidhi", age: 21, gender: "FEMALE" },
    { name: "Manisha", age: 21, gender: "FEMALE" },
    { name: "Parul", age: 21, gender: "FEMALE" },
    { name: "Subh", age: 21, gender: "MALE" },
    { name: "Nirmala", age: 21, gender: "FEMALE" },
    { name: "Amit Shah", age: 51, gender: "MALE" },
    { name: "Modi", age: 51, gender: "MALE" },
    { name: "Bangrangi", age: 41, gender: "MALE" },
    { name: "Anushka", age: 30, gender: "FEMALE" },
    { name: "Virat", age: 35, gender: "MALE" },
    { name: "Ridhima", age: 42, gender: "MALE" },
    { name: "Siddharth", age: 28, gender: "MALE" },
    { name: "Suhail", age: 41, gender: "MALE" },
    { name: "Amit", age: 51, gender: "MALE" },
    { name: "Viraj", age: 25, gender: "MALE" },
    { name: "Khoosbu", age: 21, gender: "FEMALE" },
    { name: "Nain Kamal", age: 26, gender: "FEMALE" },
  ];
  